# Makefile for IPP project 2021, FIT BUT
# Authors: Jakub Bartko, xbartk07@stud.fit.vutbr.cz

LOGIN = xbartk07
SCRIPTS = parse.php interpret.py test.php
# TESTS =
# DOCUMENTATION =

.PHONY: pack clean

pack:
	zip $(LOGIN).zip $(SCRIPTS)

clean:
	rm -f *.zip
